String.toLocaleString({
  "it": {
    "%game-intro": "Join the <strong>Cupcakes!</strong>",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation": "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer": "<strong class=\"important\">Note:</strong> This site <a href=\"https://2048cupcakes.fun\">2048cupcakes.fun</a> is a spin-off of the official version of 2048 created by Gabriele Cirulli.",
    "%credits": "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "I scored \"",
    "%tweet2": " at 2048cupcakes.fun #2048cupcakes",
    "%tile-legend": "<strong class=\"important\">Tile Legend:</strong>",
    '%2': 'vanilla birthday',
    '%4': 'bubblegum pink',
    '%8': 'sunshine vanilla',
    '%16': 'valrhona blonde ganache',
    '%32': 'chocolare peanut butter cheesecake',
    '%64': 'chocolate mint fudge',
    '%128': 'chocolate spider web',
    '%256': 'toasted marshmallow',
    '%512': 'cookies and creme',
    '%1024': 'chocolate sundae',
    '%2048': 'white chocolate peppermint',
    '%4096': '2017 Confetti Vanilla',
    '%8192': 'Rainbow',
    '%p0': 'vanilla birthday',
    '%p4': 'bubblegum pink',
    '%p8': 'sunshine vanilla',
    '%p16': 'valrhona blonde ganache',
    '%p32': 'choc. peanut butter cheesecake',
    '%p64': 'choc. mint fudge',
    '%p128': 'choc. spider web',
    '%p256': 'toasted marshmallow',
    '%p512': 'cookies and creme',
    '%p1024': 'choc. sundae',
    '%p2048': 'white choc. peppermint',
    '%p4096': '2017 Confetti Vanilla',
    '%p8192': 'Rainbow'

  },

  "en": {
    "%game-intro": "Join the <strong>Cupcakes!</strong>",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation": "<strong class=\"important\">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>",
    "%disclaimer": "<strong class=\"important\">Note:</strong> This site <a href=\"https://2048cupcakes.fun\">2048cupcakes.funs</a> is a spin-off of the official version of 2048 created by Gabriele Cirulli.",
    "%credits": "Cupcakes images by <a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>.",
    "%tweet1": "I scored \"",
    "%tweet2": " at 2048cupcakes.fun #2048cupcakes",
    "%tile-legend": "<strong class=\"important\">Tile Legend:</strong>",
    '%2': 'vanilla birthday',
    '%4': 'bubblegum pink',
    '%8': 'sunshine vanilla',
    '%16': 'valrhona blonde ganache',
    '%32': 'chocolare peanut butter cheesecake',
    '%64': 'chocolate mint fudge',
    '%128': 'chocolate spider web',
    '%256': 'toasted marshmallow',
    '%512': 'cookies and creme',
    '%1024': 'chocolate sundae',
    '%2048': 'white chocolate peppermint',
    '%4096': '2017 Confetti Vanilla',
    '%8192': 'Rainbow',
    '%p0': 'vanilla birthday',
    '%p4': 'bubblegum pink',
    '%p8': 'sunshine vanilla',
    '%p16': 'valrhona blonde ganache',
    '%p32': 'choc. peanut butter cheesecake',
    '%p64': 'choc. mint fudge',
    '%p128': 'choc. spider web',
    '%p256': 'toasted marshmallow',
    '%p512': 'cookies and creme',
    '%p1024': 'choc. sundae',
    '%p2048': 'white choc. peppermint',
    '%p4096': '2017 Confetti Vanilla',
    '%p8192': 'Rainbow'
  }
  ,
  "zh": {
    "%game-intro": "加入<strong>纸杯蛋糕大战！</strong>",
    "%restart-button": "重新开始",
    "%keep-playing-button": "继续游戏",
    "%retry-button": "重试",
    "%game-won": "你赢了！",
    "%game-over": "游戏结束！",
    "%game-explanation": "<strong class=\"important\">如何玩：</strong>使用你的<strong>箭头键</strong>移动瓷砖。当两个有相同符号的瓷砖接触时，它们就<strong>会合并！</strong>",
    "%disclaimer": "<strong class=\"important\">注意：</strong>本站点<a href=\"https://2048cupcakes.fun\">2048cupcakes.fun</a>是官方2048游戏的一个衍生版本，由Gabriele Cirulli创建。",
    "%credits": "纸杯蛋糕图片由<a href=\"http://www.georgetowncupcake.com/\" title=\"Georgetown Cupcake | DC Cupcakes | About\">Georgetown Cupcake</a>提供。",
    "%tweet1": "我在2048cupcakes.fun纸杯蛋糕游戏中得了\"",
    "%tweet2": "\"分 #2048cupcakes",
    "%tile-legend": "<strong class=\"important\">瓷砖图例：</strong>",
    '%2': '香草生日蛋糕',
    '%4': '泡泡糖粉',
    '%8': '阳光香草',
    '%16': '瓦尔罗纳白巧克力酱',
    '%32': '巧克力花生酱芝士蛋糕',
    '%64': '巧克力薄荷软糖',
    '%128': '巧克力蜘蛛网',
    '%256': '烤棉花糖',
    '%512': '曲奇和奶油',
    '%1024': '巧克力圣代',
    '%2048': '白巧克力薄荷',
    '%4096': '2017五彩香草',
    '%8192': '彩虹',
    '%p0': '香草生日蛋糕',
    '%p4': '泡泡糖粉',
    '%p8': '阳光香草',
    '%p16': '瓦尔罗纳白巧克力酱',
    '%p32': '巧克力花生酱芝士蛋糕',
    '%p64': '巧克力薄荷软糖',
    '%p128': '巧克力蜘蛛网',
    '%p256': '烤棉花糖',
    '%p512': '曲奇和奶油',
    '%p1024': '巧克力圣代',
    '%p2048': '白巧克力薄荷',
    '%p4096': '2017五彩香草',
    '%p8192': '彩虹'
  }
});
