String.toLocaleString({
  it: {
    "%game-intro": "Join the <strong>Cupcakes!</strong>",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation":
      '<strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>',
    "%disclaimer":
      '<strong class="important">Note:</strong> This site <a href="https://2048cupcakes.fun">2048cupcakes.fun</a> is a spin-off of the official version of 2048 created by Gabriele Cirulli.',
    "%credits":
      'Cupcakes images by <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": 'I scored "',
    "%tweet2": " at 2048cupcakes.fun #2048cupcakes",
    "%tile-legend": '<strong class="important">Tile Legend:</strong>',
    "%2": "vanilla birthday",
    "%4": "bubblegum pink",
    "%8": "sunshine vanilla",
    "%16": "valrhona blonde ganache",
    "%32": "chocolare peanut butter cheesecake",
    "%64": "chocolate mint fudge",
    "%128": "chocolate spider web",
    "%256": "toasted marshmallow",
    "%512": "cookies and creme",
    "%1024": "chocolate sundae",
    "%2048": "white chocolate peppermint",
    "%4096": "2017 Confetti Vanilla",
    "%8192": "Rainbow",
    "%p0": "vanilla birthday",
    "%p4": "bubblegum pink",
    "%p8": "sunshine vanilla",
    "%p16": "valrhona blonde ganache",
    "%p32": "choc. peanut butter cheesecake",
    "%p64": "choc. mint fudge",
    "%p128": "choc. spider web",
    "%p256": "toasted marshmallow",
    "%p512": "cookies and creme",
    "%p1024": "choc. sundae",
    "%p2048": "white choc. peppermint",
    "%p4096": "2017 Confetti Vanilla",
    "%p8192": "Rainbow",
  },

  en: {
    "%game-intro": "Join the <strong>Cupcakes!</strong>",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation":
      '<strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>',
    "%disclaimer":
      '<strong class="important">Note:</strong> This site <a href="https://2048cupcakes.fun">2048cupcakes.funs</a> is a spin-off of the official version of 2048 created by Gabriele Cirulli.',
    "%credits":
      'Cupcakes images by <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": 'I scored "',
    "%tweet2": " at 2048cupcakes.fun #2048cupcakes",
    "%tile-legend": '<strong class="important">Tile Legend:</strong>',
    "%2": "vanilla birthday",
    "%4": "bubblegum pink",
    "%8": "sunshine vanilla",
    "%16": "valrhona blonde ganache",
    "%32": "chocolare peanut butter cheesecake",
    "%64": "chocolate mint fudge",
    "%128": "chocolate spider web",
    "%256": "toasted marshmallow",
    "%512": "cookies and creme",
    "%1024": "chocolate sundae",
    "%2048": "white chocolate peppermint",
    "%4096": "2017 Confetti Vanilla",
    "%8192": "Rainbow",
    "%p0": "vanilla birthday",
    "%p4": "bubblegum pink",
    "%p8": "sunshine vanilla",
    "%p16": "valrhona blonde ganache",
    "%p32": "choc. peanut butter cheesecake",
    "%p64": "choc. mint fudge",
    "%p128": "choc. spider web",
    "%p256": "toasted marshmallow",
    "%p512": "cookies and creme",
    "%p1024": "choc. sundae",
    "%p2048": "white choc. peppermint",
    "%p4096": "2017 Confetti Vanilla",
    "%p8192": "Rainbow",
  },
  zh: {
    "%game-intro": "加入<strong>纸杯蛋糕大战！</strong>",
    "%restart-button": "重新开始",
    "%keep-playing-button": "继续游戏",
    "%retry-button": "重试",
    "%game-won": "你赢了！",
    "%game-over": "游戏结束！",
    "%game-explanation":
      '<strong class="important">如何玩：</strong>使用你的<strong>箭头键</strong>移动瓷砖。当两个有相同符号的瓷砖接触时，它们就<strong>会合并！</strong>',
    "%disclaimer":
      '<strong class="important">注意：</strong>本站点<a href="https://2048cupcakes.fun">2048cupcakes.fun</a>是官方2048游戏的一个衍生版本，由Gabriele Cirulli创建。',
    "%credits":
      '纸杯蛋糕图片由<a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>提供。',
    "%tweet1": '我在2048cupcakes.fun纸杯蛋糕游戏中得了"',
    "%tweet2": '"分 #2048cupcakes',
    "%tile-legend": '<strong class="important">瓷砖图例：</strong>',
    "%2": "香草生日蛋糕",
    "%4": "泡泡糖粉",
    "%8": "阳光香草",
    "%16": "瓦尔罗纳白巧克力酱",
    "%32": "巧克力花生酱芝士蛋糕",
    "%64": "巧克力薄荷软糖",
    "%128": "巧克力蜘蛛网",
    "%256": "烤棉花糖",
    "%512": "曲奇和奶油",
    "%1024": "巧克力圣代",
    "%2048": "白巧克力薄荷",
    "%4096": "2017五彩香草",
    "%8192": "彩虹",
    "%p0": "香草生日蛋糕",
    "%p4": "泡泡糖粉",
    "%p8": "阳光香草",
    "%p16": "瓦尔罗纳白巧克力酱",
    "%p32": "巧克力花生酱芝士蛋糕",
    "%p64": "巧克力薄荷软糖",
    "%p128": "巧克力蜘蛛网",
    "%p256": "烤棉花糖",
    "%p512": "曲奇和奶油",
    "%p1024": "巧克力圣代",
    "%p2048": "白巧克力薄荷",
    "%p4096": "2017五彩香草",
    "%p8192": "彩虹",
  },
  fr: {
    "%game-intro": "Rejoignez les <strong>Cupcakes !</strong>",
    "%restart-button": "Rejouer",
    "%keep-playing-button": "Continuer",
    "%retry-button": "Réessayer",
    "%game-won": "Vous avez gagné !",
    "%game-over": "Partie terminée !",
    "%game-explanation":
      '<strong class="important">Comment jouer :</strong> Utilisez vos <strong>flèches</strong> pour déplacer les tuiles. Quand deux tuiles avec le même symbole se touchent, elles <strong>fusionnent !</strong>',
    "%disclaimer":
      '<strong class="important">Note :</strong> Ce site <a href="https://2048cupcakes.fun">2048cupcakes.fun</a> est une variante de la version officielle de 2048 créée par Gabriele Cirulli.',
    "%credits":
      'Images de cupcakes par <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": "J'ai marqué \"",
    "%tweet2": " sur 2048cupcakes.fun #2048cupcakes",
    "%tile-legend": '<strong class="important">Légende des tuiles :</strong>',
    "%2": "vanille anniversaire",
    "%4": "rose bubble-gum",
    "%8": "vanille ensoleillée",
    "%16": "ganache blonde Valrhona",
    "%32": "cheesecake au beurre de cacahuète au chocolat",
    "%64": "fudge chocolat-menthe",
    "%128": "toile d'araignée au chocolat",
    "%256": "guimauve grillée",
    "%512": "cookies et crème",
    "%1024": "sundae au chocolat",
    "%2048": "chocolat blanc à la menthe",
    "%4096": "Vanille Confetti 2017",
    "%8192": "Arc-en-ciel",
    // Les versions abrégées (p0, p4, etc.) restent en anglais pour la concision
  },

  es: {
    "%game-intro": "¡Únete a los <strong>Cupcakes!</strong>",
    "%restart-button": "Jugar de nuevo",
    "%keep-playing-button": "Seguir jugando",
    "%retry-button": "Reintentar",
    "%game-won": "¡Has ganado!",
    "%game-over": "¡Juego terminado!",
    "%game-explanation":
      '<strong class="important">Cómo jugar:</strong> Usa tus <strong>teclas de flecha</strong> para mover las fichas. Cuando dos fichas con el mismo símbolo se tocan, ¡se <strong>fusionan!</strong>',
    "%disclaimer":
      '<strong class="important">Nota:</strong> Este sitio <a href="https://2048cupcakes.fun">2048cupcakes.fun</a> es una variante de la versión oficial de 2048 creada por Gabriele Cirulli.',
    "%credits":
      'Imágenes de cupcakes por <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": 'He conseguido "',
    "%tweet2": " en 2048cupcakes.fun #2048cupcakes",
    "%tile-legend": '<strong class="important">Leyenda de fichas:</strong>',
    "%2": "vainilla cumpleaños",
    "%4": "rosa chicle",
    "%8": "vainilla soleada",
    "%16": "ganache rubia Valrhona",
    "%32": "tarta de queso con mantequilla de cacahuete y chocolate",
    "%64": "fudge de chocolate y menta",
    "%128": "telaraña de chocolate",
    "%256": "malvavisco tostado",
    "%512": "galletas y crema",
    "%1024": "sundae de chocolate",
    "%2048": "chocolate blanco con menta",
    "%4096": "Vainilla Confeti 2017",
    "%8192": "Arcoíris",
    // Versiones abreviadas en inglés
  },
  ja: {
    "%game-intro": "<strong>カップケーキ</strong>に参加しよう！",
    "%restart-button": "もう一度プレイ",
    "%keep-playing-button": "続ける",
    "%retry-button": "リトライ",
    "%game-won": "勝利！",
    "%game-over": "ゲームオーバー！",
    "%game-explanation":
      '<strong class="important">遊び方：</strong><strong>矢印キー</strong>を使ってタイルを動かします。同じシンボルのタイルが触れると、<strong>合体します！</strong>',
    "%disclaimer":
      '<strong class="important">注意：</strong>このサイト<a href="https://2048cupcakes.fun">2048cupcakes.fun</a>は、Gabriele Cirulliが作成した公式版2048のスピンオフです。',
    "%credits":
      'カップケーキの画像提供：<a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>',
    "%tweet1": '2048cupcakes.funで"',
    "%tweet2": '"点を獲得しました #2048cupcakes',
    "%tile-legend": '<strong class="important">タイルの説明：</strong>',
    "%2": "バニラバースデー",
    "%4": "バブルガムピンク",
    "%8": "サンシャインバニラ",
    "%16": "ヴァローナブロンドガナッシュ",
    "%32": "チョコレートピーナッツバターチーズケーキ",
    "%64": "チョコミントファッジ",
    "%128": "チョコレートスパイダーウェブ",
    "%256": "トーストマシュマロ",
    "%512": "クッキー＆クリーム",
    "%1024": "チョコレートサンデー",
    "%2048": "ホワイトチョコレートペパーミント",
    "%4096": "2017コンフェティバニラ",
    "%8192": "レインボー",
    // 省略版は英語のまま
  },

  de: {
    "%game-intro": "Mach mit bei den <strong>Cupcakes!</strong>",
    "%restart-button": "Nochmal spielen",
    "%keep-playing-button": "Weiterspielen",
    "%retry-button": "Erneut versuchen",
    "%game-won": "Du hast gewonnen!",
    "%game-over": "Spiel vorbei!",
    "%game-explanation":
      '<strong class="important">Spielanleitung:</strong> Benutze deine <strong>Pfeiltasten</strong>, um die Kacheln zu bewegen. Wenn zwei Kacheln mit dem gleichen Symbol sich berühren, <strong>verschmelzen sie!</strong>',
    "%disclaimer":
      '<strong class="important">Hinweis:</strong> Diese Seite <a href="https://2048cupcakes.fun">2048cupcakes.fun</a> ist eine Abwandlung der offiziellen Version von 2048, erstellt von Gabriele Cirulli.',
    "%credits":
      'Cupcake-Bilder von <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": 'Ich habe "',
    "%tweet2": " bei 2048cupcakes.fun erreicht #2048cupcakes",
    "%tile-legend": '<strong class="important">Kachel-Legende:</strong>',
    "%2": "Vanille Geburtstag",
    "%4": "Kaugummi Rosa",
    "%8": "Sonnenschein Vanille",
    "%16": "Valrhona Blonde Ganache",
    "%32": "Schokoladen-Erdnussbutter-Käsekuchen",
    "%64": "Schokoladen-Minz-Fudge",
    "%128": "Schokoladen-Spinnennetz",
    "%256": "Geröstetes Marshmallow",
    "%512": "Kekse und Creme",
    "%1024": "Schokoladen-Eisbecher",
    "%2048": "Weiße Schokolade Pfefferminz",
    "%4096": "2017 Konfetti Vanille",
    "%8192": "Regenbogen",
    // Abgekürzte Versionen bleiben auf Englisch
  },
});
